%define git a29d6e9

Name:           bbcp
Version:        15.02.03.00.1
Release:        2%{?git:.git.%{git}}%{?dist}
Summary:        Securely and quickly copy data from source to target

License:        LGPLv3+
URL:            http://www.slac.stanford.edu/~abh/bbcp/
Source0:        bbcp.git.a29d6e9.tar.xz
# From http://www.slac.stanford.edu/~abh/bbcp/bbcp.git
# Tarball producing: ./%%{SOURCE1} %%{git}
Source1:        bbcp.get.git

BuildRequires:  zlib-devel, openssl-devel
BuildRequires:  help2man

%description
Fast copying tools over network. Replacement for scp, rsync for big amount of
transfer with numerous optimizations and tuning capability.

%prep
%setup -q -n %{name}.%{git}


%build
cd src
# Hack to workaround of errors:
# make[2]: *** No rule to make target `makeLinuxppc64'.  Stop.
# make[2]: *** No rule to make target 'makeLinuxarmv7l'.  Stop.
# Unfortunately checks hardcoded, so, hacking required
if [ 'ppc64' = `uname -i` -o 'armv7l' = `uname -i` ]; then
 sed -i.arch 's#@make makeLinux`/bin/uname -i`#@make makeLinuxx86_64#' Makefile
fi
# Honor our build flags
sed -i.flags 's/LNXOPT     =/LNXOPT     +=/' Makefile
LNXOPT="%{optflags}" DEST_SYSNAME=linux make %{?_smp_mflags}

%install
# There no install target in Makefile. Do it manually
install -Dm 0755 bin/linux/%{name} %{buildroot}%{_bindir}/%{name}

install -d %{buildroot}/%{_mandir}/man1
help2man -N %{buildroot}/%{_bindir}/%{name} > %{buildroot}/%{_mandir}/man1/%{name}.1

%files
%license src/COPYING.LESSER
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1*

%changelog
* Wed Apr 15 2015 Pavel Alexeev <Pahan@Hubbitus.info> - 15.02.03.00.1-2.git.a29d6e9
- By mail suggestion of Victor Museteanu (thanks):
	o Add honor Fedora build flags.
	o Add man, generated by help2man (I'm doubt what it is imporvment, but let it be)

* Mon Mar 23 2015 Pavel Alexeev (aka Pahan-Hubbitus) <Pahan@Hubbitus.info> - 15.02.03.00.1-1.git.a29d6e9
- Initial spec
